//go:build !ignore_autogenerated


package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *BackupOptions) DeepCopyInto(out *BackupOptions) {
	*out = *in
	in.Encryption.DeepCopyInto(&out.Encryption)
}

func (in *BackupOptions) DeepCopy() *BackupOptions {
	if in == nil {
		return nil
	}
	out := new(BackupOptions)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupReference) DeepCopyInto(out *BackupReference) {
	*out = *in
}

func (in *BackupReference) DeepCopy() *BackupReference {
	if in == nil {
		return nil
	}
	out := new(BackupReference)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackupStorageSpec) DeepCopyInto(out *BackupStorageSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *BackupStorageSpec) DeepCopy() *BackupStorageSpec {
	if in == nil {
		return nil
	}
	out := new(BackupStorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseAccess) DeepCopyInto(out *DatabaseAccess) {
	*out = *in
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]SchemaAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DatabaseAccess) DeepCopy() *DatabaseAccess {
	if in == nil {
		return nil
	}
	out := new(DatabaseAccess)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseFilter) DeepCopyInto(out *DatabaseFilter) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DatabaseFilter) DeepCopy() *DatabaseFilter {
	if in == nil {
		return nil
	}
	out := new(DatabaseFilter)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]DatabaseAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *EncryptionSpec) DeepCopyInto(out *EncryptionSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

func (in *EncryptionSpec) DeepCopy() *EncryptionSpec {
	if in == nil {
		return nil
	}
	out := new(EncryptionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HASpec) DeepCopyInto(out *HASpec) {
	*out = *in
}

func (in *HASpec) DeepCopy() *HASpec {
	if in == nil {
		return nil
	}
	out := new(HASpec)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceRestoreStatus) DeepCopyInto(out *InstanceRestoreStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

func (in *InstanceRestoreStatus) DeepCopy() *InstanceRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceSelector) DeepCopyInto(out *InstanceSelector) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *InstanceSelector) DeepCopy() *InstanceSelector {
	if in == nil {
		return nil
	}
	out := new(InstanceSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	out.Prometheus = in.Prometheus
}

func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PasswordRotationPolicy) DeepCopyInto(out *PasswordRotationPolicy) {
	*out = *in
}

func (in *PasswordRotationPolicy) DeepCopy() *PasswordRotationPolicy {
	if in == nil {
		return nil
	}
	out := new(PasswordRotationPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *PasswordSpec) DeepCopyInto(out *PasswordSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.RotationPolicy != nil {
		in, out := &in.RotationPolicy, &out.RotationPolicy
		*out = new(PasswordRotationPolicy)
		**out = **in
	}
}

func (in *PasswordSpec) DeepCopy() *PasswordSpec {
	if in == nil {
		return nil
	}
	out := new(PasswordSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresBackup) DeepCopyInto(out *PostgresBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PostgresBackup) DeepCopy() *PostgresBackup {
	if in == nil {
		return nil
	}
	out := new(PostgresBackup)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresBackupList) DeepCopyInto(out *PostgresBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresBackupList) DeepCopy() *PostgresBackupList {
	if in == nil {
		return nil
	}
	out := new(PostgresBackupList)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresBackupSpec) DeepCopyInto(out *PostgresBackupSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	in.Storage.DeepCopyInto(&out.Storage)
	out.RetentionPolicy = in.RetentionPolicy
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(InstanceSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Options.DeepCopyInto(&out.Options)
}

func (in *PostgresBackupSpec) DeepCopy() *PostgresBackupSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresBackupSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresBackupStatus) DeepCopyInto(out *PostgresBackupStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Database.DeepCopyInto(&out.Database)
}

func (in *PostgresBackupStatus) DeepCopy() *PostgresBackupStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresBackupStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresCluster) DeepCopyInto(out *PostgresCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PostgresCluster) DeepCopy() *PostgresCluster {
	if in == nil {
		return nil
	}
	out := new(PostgresCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresClusterList) DeepCopyInto(out *PostgresClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresClusterList) DeepCopy() *PostgresClusterList {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresClusterSpec) DeepCopyInto(out *PostgresClusterSpec) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]PostgresInstanceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.HighAvailability = in.HighAvailability
	in.Backup.DeepCopyInto(&out.Backup)
	in.Storage.DeepCopyInto(&out.Storage)
	out.Resources = in.Resources
	in.Database.DeepCopyInto(&out.Database)
	out.Monitoring = in.Monitoring
}

func (in *PostgresClusterSpec) DeepCopy() *PostgresClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresClusterStatus) DeepCopyInto(out *PostgresClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastBackup != nil {
		in, out := &in.LastBackup, &out.LastBackup
		*out = (*in).DeepCopy()
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]PostgresInstanceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresClusterStatus) DeepCopy() *PostgresClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresInstanceSpec) DeepCopyInto(out *PostgresInstanceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		**out = **in
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *PostgresInstanceSpec) DeepCopy() *PostgresInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresInstanceStatus) DeepCopyInto(out *PostgresInstanceStatus) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *PostgresInstanceStatus) DeepCopy() *PostgresInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresRestore) DeepCopyInto(out *PostgresRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PostgresRestore) DeepCopy() *PostgresRestore {
	if in == nil {
		return nil
	}
	out := new(PostgresRestore)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresRestoreList) DeepCopyInto(out *PostgresRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresRestoreList) DeepCopy() *PostgresRestoreList {
	if in == nil {
		return nil
	}
	out := new(PostgresRestoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresRestoreSpec) DeepCopyInto(out *PostgresRestoreSpec) {
	*out = *in
	out.BackupRef = in.BackupRef
	out.TargetCluster = in.TargetCluster
	in.Options.DeepCopyInto(&out.Options)
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(InstanceSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *PostgresRestoreSpec) DeepCopy() *PostgresRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresRestoreStatus) DeepCopyInto(out *PostgresRestoreStatus) {
	*out = *in
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InstanceStatuses != nil {
		in, out := &in.InstanceStatuses, &out.InstanceStatuses
		*out = make([]InstanceRestoreStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresRestoreStatus) DeepCopy() *PostgresRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresUser) DeepCopyInto(out *PostgresUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PostgresUser) DeepCopy() *PostgresUser {
	if in == nil {
		return nil
	}
	out := new(PostgresUser)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresUserList) DeepCopyInto(out *PostgresUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresUserList) DeepCopy() *PostgresUserList {
	if in == nil {
		return nil
	}
	out := new(PostgresUserList)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PostgresUserSpec) DeepCopyInto(out *PostgresUserSpec) {
	*out = *in
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(ClusterReference)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(PasswordSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InstanceSelector != nil {
		in, out := &in.InstanceSelector, &out.InstanceSelector
		*out = new(InstanceSelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *PostgresUserSpec) DeepCopy() *PostgresUserSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresUserSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PostgresUserStatus) DeepCopyInto(out *PostgresUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPasswordChange != nil {
		in, out := &in.LastPasswordChange, &out.LastPasswordChange
		*out = (*in).DeepCopy()
	}
	if in.DatabasesGranted != nil {
		in, out := &in.DatabasesGranted, &out.DatabasesGranted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InstanceStatuses != nil {
		in, out := &in.InstanceStatuses, &out.InstanceStatuses
		*out = make([]UserInstanceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PostgresUserStatus) DeepCopy() *PostgresUserStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresUserStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PrometheusSpec) DeepCopyInto(out *PrometheusSpec) {
	*out = *in
}

func (in *PrometheusSpec) DeepCopy() *PrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
}

func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

func (in *RestoreOptions) DeepCopyInto(out *RestoreOptions) {
	*out = *in
	if in.DatabaseFilter != nil {
		in, out := &in.DatabaseFilter, &out.DatabaseFilter
		*out = new(DatabaseFilter)
		(*in).DeepCopyInto(*out)
	}
}

func (in *RestoreOptions) DeepCopy() *RestoreOptions {
	if in == nil {
		return nil
	}
	out := new(RestoreOptions)
	in.DeepCopyInto(out)
	return out
}

func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
}

func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *SchemaAccess) DeepCopyInto(out *SchemaAccess) {
	*out = *in
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SchemaAccess) DeepCopy() *SchemaAccess {
	if in == nil {
		return nil
	}
	out := new(SchemaAccess)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *UserInstanceStatus) DeepCopyInto(out *UserInstanceStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

func (in *UserInstanceStatus) DeepCopy() *UserInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(UserInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
